import { readFile, writeFile } from "node:fs/promises";
import { spawn } from "node:child_process";
import { join } from "node:path";

/**
 * One place for credentials, two places that need them.
 *
 * THE PROBLEM THIS EXISTS TO END. The same three secrets were being typed in by
 * hand into three different places, because three different runtimes want them
 * and none of them share:
 *
 *   .secrets/*.txt            the Node CLI — store:sync, sweep, report
 *   .dev.vars                 `wrangler dev`, running the Worker locally
 *   `wrangler secret put`     the DEPLOYED Worker on Cloudflare
 *
 * The captain, on being asked for a Stripe key for the third time: "what the
 * fuck are these secret keys i already filled these out 500 times & have
 * .secrets folder with these???" He is right, and worse — he was going to
 * Stripe to fetch a key that was already sitting on his own disk, and Stripe
 * only shows a live secret key once, so that road ends in rolling a key for no
 * reason.
 *
 * `.secrets/` is the single source. This copies from it. Nothing is ever typed
 * twice and nothing is ever fetched from a dashboard again.
 *
 *   npm run secrets:local     write .dev.vars from .secrets/
 *   npm run secrets:deploy    upload the same values to Cloudflare
 *
 * IT NEVER PRINTS A VALUE. Every message names a file and a length; the secrets
 * themselves do not reach stdout, a log, or this process's arguments — the
 * deploy path pipes them to wrangler on stdin rather than passing them as
 * arguments, which would put them in the process table.
 */

const ROOT = new URL("..", import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, "$1");
const SECRETS = join(ROOT, ".secrets");

/**
 * Worker env var -> the file in .secrets/ that holds it.
 *
 * `stripe_secret.txt` is whichever key the captain last saved — test or live.
 * The Worker cannot tell and does not need to: a test key simply produces a
 * test session. Keep the live key there once the store opens.
 */
const KEYS = [
  { env: "STRIPE_SECRET_KEY", file: "stripe_secret.txt", required: true },
  { env: "PRINTIFY_API_TOKEN", file: "printify_token.txt", required: true },
  {
    env: "STRIPE_WEBHOOK_SECRET",
    file: "stripe_webhook_secret.txt",
    required: false,
    note: "only exists after the webhook endpoint is created — MANUAL.md step 12",
  },
];

async function read(entry) {
  try {
    const value = (await readFile(join(SECRETS, entry.file), "utf8")).trim();
    return value.length ? value : null;
  } catch {
    return null;
  }
}

async function collect() {
  const found = [];
  for (const entry of KEYS) {
    const value = await read(entry);
    if (value) {
      found.push({ ...entry, value });
      console.log(`  ${entry.env.padEnd(24)} .secrets/${entry.file.padEnd(28)} ${value.length} chars`);
    } else if (entry.required) {
      console.error(`  ${entry.env.padEnd(24)} MISSING — expected .secrets/${entry.file}`);
    } else {
      console.log(`  ${entry.env.padEnd(24)} not set — ${entry.note}`);
    }
  }
  if (KEYS.some((k) => k.required && !found.some((f) => f.env === k.env))) {
    console.error("\nA required secret is missing. Nothing was written.");
    process.exit(1);
  }
  return found;
}

/** `.dev.vars`, for `wrangler dev`. */
async function local() {
  console.log("Reading .secrets/\n");
  const found = await collect();
  const body =
    "# GENERATED by `npm run secrets:local` from .secrets/ — do not edit.\n" +
    "# Re-run it after changing anything in .secrets/. Gitignored.\n\n" +
    found.map((f) => `${f.env}=${f.value}`).join("\n") +
    "\n";
  await writeFile(join(ROOT, ".dev.vars"), body);
  console.log(`\nWrote .dev.vars with ${found.length} secret(s). Restart \`wrangler dev\` to pick them up.`);
}

/** The deployed Worker. Values go over stdin, never in an argument. */
async function deploy() {
  console.log("Reading .secrets/\n");
  const found = await collect();
  console.log("\nUploading to Cloudflare…\n");
  for (const entry of found) {
    const code = await new Promise((resolve) => {
      const child = spawn("npx", ["wrangler", "secret", "put", entry.env], {
        cwd: ROOT,
        stdio: ["pipe", "inherit", "inherit"],
        shell: process.platform === "win32",
      });
      child.stdin.end(entry.value);
      child.on("close", resolve);
    });
    if (code !== 0) {
      console.error(`\n${entry.env} failed (exit ${code}). Stopping.`);
      process.exit(1);
    }
  }
  console.log(`\n${found.length} secret(s) uploaded. \`npx wrangler secret list\` shows the names.`);
}

const mode = process.argv[2];
if (mode === "local") await local();
else if (mode === "deploy") await deploy();
else {
  console.error("secrets.mjs local | deploy");
  console.error("  local   write .dev.vars from .secrets/  (for `wrangler dev`)");
  console.error("  deploy  upload the same values to the deployed Worker");
  process.exit(2);
}
