import catalog from "../../../data/products.json";
import type { CatalogProduct } from "../../../../../packages/store/src/basket";
import { feedRows, renderFeed } from "../../../../../packages/store/src/feed";
import { SITE_URL } from "../../../lib/meta";

/**
 * The Google Merchant Center feed, generated BY THE NEXT BUILD ITSELF.
 *
 * **This is a route rather than a script for one reason: what the deploy runs
 * is not knowable from inside this repository.** `apps/web/out/` is gitignored
 * and Cloudflare rebuilds from pushed source, so the feed has to be written by
 * whatever command the dashboard is configured with. A generator hanging off
 * `npm run build:site` is only correct while that is the configured command —
 * change it to `next build apps/web`, or add a second host, and the feed
 * silently stops being written with nothing to say so.
 *
 * A static route handler cannot be skipped: `next build` renders it at build
 * time like any other page, so the feed exists wherever the site does.
 *
 * Everything it says is decided in `packages/store/src/feed.ts`, where
 * `npm test` asserts it. This is serialisation and nothing else.
 */
export const dynamic = "force-static";

export function GET(): Response {
  const products = (catalog as { products: unknown[] }).products as CatalogProduct[];
  const { rows } = feedRows(products, SITE_URL);

  return new Response(renderFeed(rows, SITE_URL), {
    headers: { "content-type": "application/xml; charset=utf-8" },
  });
}
