/**
 * Minimal HTML helpers shared by the parsers.
 *
 * Zero dependencies, per the project's ten-year durability goal. These pages
 * are machine-generated by two known platforms, so a regex reader is adequate
 * and honest about its limits — it is not a general HTML parser.
 */

/** Strip tags to text, decode the entities these pages actually use. */
export function text(html: string): string {
  return html
    .replace(/<[^>]+>/g, " ")
    .replace(/&nbsp;/g, " ")
    .replace(/&#39;/g, "'")
    .replace(/&quot;/g, '"')
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    // &amp; LAST: decoding it first would turn "&amp;lt;" into "<".
    .replace(/&amp;/g, "&")
    .replace(/\s+/g, " ")
    .trim();
}

/**
 * Cells of one row, IN ORDER, INCLUDING EMPTY ONES.
 *
 * Dropping empty cells shifts every subsequent value into the wrong column —
 * a hazard hit repeatedly on this project (§2.9). An empty cell is positional
 * information and, per §2.4, is NOT zero.
 */
export function cellsOf(row: string): string[] {
  return (row.match(/<t[dh][^>]*>[\s\S]*?<\/t[dh]>/g) ?? []).map(text);
}

export function rowsOf(table: string): string[] {
  return table.match(/<tr[^>]*>[\s\S]*?<\/tr>/g) ?? [];
}
